
```yaml
# media-rotator.config.yml
# Opinionated, distilled preferences for a long-running media rotation service
# tuned for Brayden’s DietPi + Jellyfin + Radarr/Sonarr setup

identity:
  owner: "Brayden"
  host_role: "dietpi-media"
  philosophy: "high-variety, low-hoarding, constantly refreshed"
  bias:
    - indie
    - critically_acclaimed
    - off-mainstream
    - genre_rotation_over_franchise_completion

paths:
  jellyfin:
    movies: "/mnt/netstorage/Media/RotatingMovies"
    tv: "/mnt/netstorage/Media/RotatingTV"
  cache:
    metadata: "/var/lib/media-rotator/cache"
    state: "/var/lib/media-rotator/state.db"
    logs: "/var/log/media-rotator"

storage_limits:
  movies:
    max_size_tb: 4.0
    target_free_percent: 12
  tv:
    max_size_tb: 4.0
    target_free_percent: 10
  eviction_policy: "oldest_unwatched_first"

trakt:
  auth_env: "TRAKT_API_KEY"
  user: "braydio"
  lists:
    movies:
      primary:
        - "Official Top Lists: Indie Films"
        - "Letterboxd: Popular With Friends"
        - "A24 Essentials"
        - "Rotten Tomatoes: Hidden Gems"
        - "Criterion Collection Picks"
      spice:
        - "Cult Classics"
        - "Foreign Language Essentials"
        - "90s Weird Cinema"
    tv:
      primary:
        - "Critically Acclaimed TV"
        - "Limited Series Essentials"
        - "FX / HBO Prestige"
      spice:
        - "Animated Adult Series"
        - "British Panel & Comedy"
  rotation_weights:
    primary: 0.7
    spice: 0.3

radarr:
  url: "http://localhost:7878"
  api_key_env: "RADARR_API_KEY"
  quality_profile: "HD-1080p-Reasonable"
  minimum_availability: "released"
  monitored: true
  tags:
    - "rotating"
    - "trakt"
  add_options:
    search_for_movie: true
    root_folder: "/mnt/netstorage/Media/RotatingMovies"
  retention:
    min_days_present: 21
    protect_if_watched: true

sonarr:
  url: "http://localhost:8989"
  api_key_env: "SONARR_API_KEY"
  quality_profile: "HD-1080p-Reasonable"
  season_handling: "complete_seasons_only"
  monitored: true
  tags:
    - "rotating"
    - "trakt"
  add_options:
    search_for_series: true
    root_folder: "/mnt/netstorage/Media/RotatingTV"
  retention:
    min_days_present: 30
    protect_if_in_progress: true

jellyfin:
  url: "http://localhost:8096"
  api_key_env: "JELLYFIN_API_KEY"
  behavior:
    rescan_on_change: true
    refresh_metadata: true
    prefer_trakt_metadata: true

rotation_engine:
  cadence:
    check_interval_hours: 6
    max_additions_per_run:
      movies: 2
      tv: 1
  diversity_rules:
    max_same_genre_percent: 25
    max_same_year_span: 5
    avoid_back_to_back_franchises: true
  eviction_triggers:
    - storage_threshold_exceeded
    - stale_unwatched_days_exceeded
  stale_definition:
    movie_unwatched_days: 45
    tv_unwatched_days: 60

user_experience_bias:
  girlfriend_factor:
    enabled: true
    boost:
      - romance
      - comedy
      - comfort_tv
    avoid:
      - hyperviolent
      - bleak_for_bleaks_sake
  novelty_preference: "high"
  rewatch_penalty: true

safety:
  dry_run: false
  never_delete:
    tags:
      - "favorite"
      - "do-not-rotate"
  log_level: "info"
  fail_closed: true

telemetry:
  track_decisions: true
  export_stats: "/var/lib/media-rotator/rotation_stats.json"
```
