services:
  transcode_notifier:
    build: .
    container_name: transcode_notifier
    ports:
      - "8099:8099"
    volumes:
      - /home/pi:/app/host_home_pi
      - /mnt/netstorage:/mnt/netstorage
    restart: unless-stopped
